<?php

return [
    'sign_in' => 'Sign In',
    'go_to_login' => 'Go to Login',
    'failed' => 'No account matching those credentials could be found.',

    'forgot_password' => [
        'label' => 'Forgot Password?',
        'label_help' => 'Enter your account email address to receive instructions on resetting your password.',
        'button' => 'Recover Account',
    ],

    'reset_password' => [
        'button' => 'Reset and Sign In',
    ],

    'two_factor' => [
        'label' => '2-Factor Token',
        'title' => 'Two Factor Authentication',
        'label_help' => 'This account requires a second layer of authentication in order to continue. Please enter the code generated by your device to complete this login.',
        'checkpoint_failed' => 'The two-factor authentication token was invalid.',
        'recovery_code_help' => 'Enter one of the recovery codes generated when you setup 2-Factor authentication on this account in order to continue.',
        'token_help' => 'Enter the two-factor token displayed by your device.',
        'lost_device' => 'I\'ve Lost My Device',
        'have_device' => 'I Have My Device',
    ],

    'throttle' => 'Too many login attempts. Please try again in :seconds seconds.',
    'password_requirements' => 'Password must be at least 8 characters in length and should be unique to this site.',
    '2fa_must_be_enabled' => 'The administrator has required that 2-Factor Authentication be enabled for your account in order to use the Panel.',
    'validation_username_or_email_required' => 'A username or email must be provided.',
    'validation_account_password_required' => 'Please enter your account password.',
    'validation_captcha_required' => 'Please complete the captcha verification.',
    'validation_email_required' => 'Email is required.',
    'validation_email_valid' => 'Enter a valid email address.',
    'validation_new_password_required' => 'A new password is required.',
    'validation_new_password_min' => 'Your new password should be at least 8 characters in length.',
    'validation_password_confirmation_required' => 'Your new password does not match.',
    'validation_password_confirmation_mismatch' => 'Your new password does not match.',
];
